mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://172.245.10.200:3306/storage?serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    #    username: somg
    #    password: somg
    url: jdbc:mysql://localhost:3306/lee7s_shop?serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # 整合swagger的时候版本过高的解决办法
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  # 邮件配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.gmail.com
    # 发送者邮箱
    username: lee7s.qs@gmail.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: mciovxwvabjywzlf
    # 端口号465或587
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true