mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#      id-type: auto
  mapper-locations: classpath:/mapper/*.xml

#  configuration:
    ### 开启打印sql配置
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.245.10.200:3306/account_shop?serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: account_shop
    password: 6CN6Aapd2mHAAEEx
#    url: jdbc:mysql://localhost:3306/account_shop?serverTimezone=GMT%2B8&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # 整合swagger的时候版本过高的解决办法
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # redis配置
  redis:
    database: 0
    host: 75.127.13.112
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最晓空闲连接
        min-idle: 3
    # 连接超时时间（毫秒）
    password:
    timeout: 5000


  # 邮件配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.gmail.com
    # 发送者邮箱
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
#    username: lee7s.qs@gmail.com
#    password: mciovxwvabjywzlf
    username: qisomg@gmail.com
    password: sqdcczvialajvjtv
    # 端口号465或587
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true